# Generated by Django 4.0.2 on 2022-03-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_comment_delete_usercommentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='dislike',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userpostmodel',
            name='amount_of_dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
