# Generated by Django 4.0.2 on 2022-03-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userpostmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, choices=[(0, 'Communication'), (1, 'Conference Report'), (2, 'Editorial'), (3, 'Opinion'), (4, 'Perspective'), (5, 'Book Review'), (6, 'Registered Report'), (7, 'Review'), (8, 'Else')], max_length=10, null=True),
        ),
    ]
